config/routes.rb
Rails.application.routes.draw do
  resources :restaurantes

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  attr_accessor :nombre
  def initialize 
    @nombre = "Hola"
  end
  
  
  def restaurante_params
      params.require(:restaurante).permit(:nombre, :tipo, :telefono)
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:nombre, :telefono, :tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestauranteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/index.html.erb
<h1>Listing restaurantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.nombre %></td>
        <td><%= restaurante.telefono %></td>
        <td><%= restaurante.tipo %></td>
        <td><%= link_to 'Show', restaurante %></td>
        <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
        <td><%= link_to 'Destroy', restaurante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurante', new_restaurante_path %>

app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @restaurante.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @restaurante.telefono %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @restaurante.tipo %>
</p>

<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>